% MEJOR QUE ENCONTRE PARA PARAMETROS ADAPTATIVOS

    params = struct(...
        'actFunct', 1, ...
        'eta', 0.08, ...
        'alpha', 0, ...
        'arq', [2, 9, 13, 1], ...
        'epocs', 5000, ...
        'training', 700,...
        'delta', 1 ,...
        'adaptInc', 0.0001, ...
        'adaptDec', 0.01, ...
        'adaptStep', 0, ...
        'adaptM', 700 ...
    );


m = main(params.actFunct,params.eta, params.alpha, params.arq, params.epocs, ...
params.training, params.delta, params.adaptInc, params.adaptDec, params.adaptStep, params.adaptM);
save(['[' num2str(params.arq) '] '], 'm');