        
    params = struct(...
        'actFunct', 1, ...
        'eta', 0.05, ...
        'alpha', 0, ...
        'arq', [1,2,1], ...
        'epocs', 20000, ...
        'training', 700 ...
    );

    m = main(params.actFunct,params.eta,params.alpha, params.arq, params.epocs, params.training);
%     save(['1arq' num2str(params.arq) 'act func' num2str(params.actFunct) 'result.mat'], 'm');
