
% PRUEBO DISTINTAS FUNCIONES DE ACTIVACIÓN

params = struct(...
        'actFunct', 0, ...
        'expError', 0.01,...
        'eta', 0.3, ...
        'alpha', 0.3, ...
        'adaptInc', 0.0001, ...
        'adaptDec', 0.01, ...
        'adaptStep', 4, ...
        'arq', [2,15,8,1], ...
        'n', 2 ...
    );

    m = main(params.actFunct,params.expError,params.eta,params.alpha,params.adaptInc, ...
    params.adaptDec, params.adaptStep, params.arq);
    save(['arq' num2str(params.arq) 'act func' num2str(params.actFunct) 'CONPARAMSresult.mat'], 'm');